In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv('Absenteeism_preprocessed.csv')
df

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

In [3]:
df['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
df['Exessive Absenteeism'] = targets

In [6]:
df

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Exessive Absenteeism  
0                       1  
1                       0  
2                       0  
3                       1  
4                       0  
..                    ...  
695                     1  
696                     0  
697                     1  
698                     0  
699                     0  

[700 rows x 16 columns]

## A comment on the targets

In [7]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [8]:
data_with_targets = df.drop(['Absenteeism Time in Hours','Day of the week', 'Daily Work Load Average', 'Distance to Work','Month Value'], axis = 1)
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Exessive Absenteeism  
0                 30          0         2     1                     1  
1                 31          0         1     0                     0  
2                 31          0         0     0                     0  
3                 24          0         2     0                     1  
4                 30          0         2     1                     0  
..               ...        ...       ...   ...                   ...  
695               22          1         2     0                     1  
696               24          0         1     2                     0  
697               25          1         0     0                     1  
698               25          1         0     0                     0  
699               25          0         1     1                     0  

[700 rows x 11 columns]

In [9]:
x = data_with_targets.iloc[:, :-1]
y = data_with_targets.iloc[:, -1:]

print(x.columns.values)
print(y.columns.values)

['Reason_1' 'Reason_2' 'Reason_3' 'Reason_4' 'Transportation Expense'
 'Age' 'Body Mass Index' 'Education' 'Children' 'Pets']
['Exessive Absenteeism']


In [10]:
unscaled_inputs = data_with_targets.iloc[:, :-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 10 columns]

## Standarization

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

scaler.fit(unscaled_inputs)

StandardScaler()

In [13]:
from sklearn.base import BaseEstimator, TransformerMixin

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, x, y=None):
        self.scaler.fit(x[self.columns], y)
        self.mean_ = np.mean(x[self.columns])
        self.var_ = np.var(x[self.columns])
        return self
    
    def transform(self, x, y=None, copy=None):
        init_col_order = x.columns
        x_scaled = pd.DataFrame(self.scaler.transform(x[self.columns]), columns=self.columns)
        x_not_scaled = x.loc[:, ~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled, x_scaled], axis=1)[init_col_order]

In [14]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [15]:
# columns_to_scale = ['Transportation Expense',
#        'Age', 'Body Mass Index', 'Education',
#        'Children', 'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [16]:
cust_scaler = CustomScaler(columns_to_scale)

cust_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Age', 'Body Mass Index',
                      'Children', 'Pets'])

In [17]:
scaled_input = cust_scaler.transform(unscaled_inputs)
scaled_input

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0           0         0         0         1                1.005844 -0.536062   
1           0         0         0         0               -1.574681  2.130803   
2           0         0         0         1               -0.654143  0.248310   
3           1         0         0         0                0.854936  0.405184   
4           0         0         0         1                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695         1         0         0         0               -0.654143  0.562059   
696         1         0         0         0                0.040034 -1.320435   
697         1         0         0         0                1.624567 -1.320435   
698         0         0         0         1                0.190942 -0.692937   
699         0         0         0         1                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets  
0           0.767431          0  0.880469  0.268487  
1           1.002633          0 -0.019280 -0.589690  
2           1.002633          0 -0.919030 -0.589690  
3          -0.643782          0  0.880469 -0.589690  
4           0.767431          0  0.880469  0.268487  
..               ...        ...       ...       ...  
695        -1.114186          1  0.880469 -0.589690  
696        -0.643782          0 -0.019280  1.126663  
697        -0.408580          1 -0.919030 -0.589690  
698        -0.408580          1 -0.919030 -0.589690  
699        -0.408580          0 -0.019280  0.268487  

[700 rows x 10 columns]

In [18]:
# scaled_input = scaler.transform(unscaled_inputs)
# scaled_input

In [19]:
scaled_input.shape

(700, 10)

## Split the data into train & test and shuffle

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(scaled_input, targets, train_size = 0.8, random_state = 20)

In [22]:
X_train.shape

(560, 10)

In [23]:
y_train.shape

(560,)

In [24]:
X_test.shape

(140, 10)

In [25]:
y_test.shape

(140,)

## Logistic Regression Model

In [26]:
logi_reg = LogisticRegression()

logi_reg.fit(X_train, y_train)

pred = logi_reg.predict(X_test)

In [27]:
prob_pred = logi_reg.predict_proba(X_test)
prob_pred

array([[0.75636056, 0.24363944],
       [0.61004173, 0.38995827],
       [0.48598117, 0.51401883],
       [0.75636056, 0.24363944],
       [0.08342835, 0.91657165],
       [0.30365823, 0.69634177],
       [0.30370587, 0.69629413],
       [0.11544724, 0.88455276],
       [0.74012635, 0.25987365],
       [0.75636056, 0.24363944],
       [0.50687557, 0.49312443],
       [0.19574658, 0.80425342],
       [0.06188808, 0.93811192],
       [0.7036954 , 0.2963046 ],
       [0.29502612, 0.70497388],
       [0.52019154, 0.47980846],
       [0.50687557, 0.49312443],
       [0.50687557, 0.49312443],
       [0.36604835, 0.63395165],
       [0.06480905, 0.93519095],
       [0.74012635, 0.25987365],
       [0.75636056, 0.24363944],
       [0.48057117, 0.51942883],
       [0.48057117, 0.51942883],
       [0.22477894, 0.77522106],
       [0.74012635, 0.25987365],
       [0.51119197, 0.48880803],
       [0.87740066, 0.12259934],
       [0.24015546, 0.75984454],
       [0.75636056, 0.24363944],
       [0.

In [28]:
prob_pred[:, 0]

array([0.75636056, 0.61004173, 0.48598117, 0.75636056, 0.08342835,
       0.30365823, 0.30370587, 0.11544724, 0.74012635, 0.75636056,
       0.50687557, 0.19574658, 0.06188808, 0.7036954 , 0.29502612,
       0.52019154, 0.50687557, 0.50687557, 0.36604835, 0.06480905,
       0.74012635, 0.75636056, 0.48057117, 0.48057117, 0.22477894,
       0.74012635, 0.51119197, 0.87740066, 0.24015546, 0.75636056,
       0.61004173, 0.28574481, 0.30365823, 0.50687557, 0.75636056,
       0.40500603, 0.74012635, 0.21890711, 0.56177959, 0.39319888,
       0.75636056, 0.50131888, 0.74012635, 0.5922901 , 0.19163908,
       0.40139786, 0.27885325, 0.75636056, 0.75452647, 0.75636056,
       0.50131888, 0.70850542, 0.30365823, 0.75452647, 0.18015778,
       0.61004173, 0.09473432, 0.73353053, 0.67944799, 0.67944799,
       0.29411123, 0.30365823, 0.73353053, 0.22477894, 0.75640207,
       0.75636056, 0.92499441, 0.74012635, 0.23834855, 0.7036954 ,
       0.74012635, 0.68261589, 0.11723728, 0.56177959, 0.40500

In [29]:
from sklearn.metrics import accuracy_score, f1_score

In [30]:
logi_reg.score(X_train, y_train)

0.7732142857142857

In [31]:
logi_reg.score(X_test, y_test)

0.7285714285714285

In [32]:
accuracy_score(pred, y_test)

0.7285714285714285

In [33]:
f1_score(pred, y_test, average='macro')

0.7249793217535153

In [34]:
logi_reg.intercept_

array([-1.60813265])

In [35]:
logi_reg.coef_

array([[ 2.77009271,  0.93000388,  3.09198231,  0.80732617,  0.62610073,
        -0.1734875 ,  0.2877657 , -0.24074182,  0.3579971 , -0.27319814]])

In [36]:
feature_name = unscaled_inputs.columns.values

In [37]:
sum_table = pd.DataFrame (columns = ['Feature Name'], data = feature_name)

In [38]:
sum_table['Coefficient'] = np.transpose(logi_reg.coef_)
sum_table

Feature Name  Coefficient
0                Reason_1     2.770093
1                Reason_2     0.930004
2                Reason_3     3.091982
3                Reason_4     0.807326
4  Transportation Expense     0.626101
5                     Age    -0.173487
6         Body Mass Index     0.287766
7               Education    -0.240742
8                Children     0.357997
9                    Pets    -0.273198

In [39]:
sum_table.index = sum_table.index+1

In [40]:
sum_table.loc[0] = ['Intercept', logi_reg.intercept_[0]]
sum_table = sum_table.sort_index()
sum_table

Feature Name  Coefficient
0                Intercept    -1.608133
1                 Reason_1     2.770093
2                 Reason_2     0.930004
3                 Reason_3     3.091982
4                 Reason_4     0.807326
5   Transportation Expense     0.626101
6                      Age    -0.173487
7          Body Mass Index     0.287766
8                Education    -0.240742
9                 Children     0.357997
10                    Pets    -0.273198

## Interpreting the coefficients

In [41]:
sum_table['Odds_ratio'] = np.exp(sum_table.Coefficient)

In [42]:
sum_table

Feature Name  Coefficient  Odds_ratio
0                Intercept    -1.608133    0.200261
1                 Reason_1     2.770093   15.960114
2                 Reason_2     0.930004    2.534519
3                 Reason_3     3.091982   22.020687
4                 Reason_4     0.807326    2.241905
5   Transportation Expense     0.626101    1.870304
6                      Age    -0.173487    0.840728
7          Body Mass Index     0.287766    1.333445
8                Education    -0.240742    0.786045
9                 Children     0.357997    1.430461
10                    Pets    -0.273198    0.760942

In [43]:
sum_table.sort_values('Odds_ratio', ascending=False)

Feature Name  Coefficient  Odds_ratio
3                 Reason_3     3.091982   22.020687
1                 Reason_1     2.770093   15.960114
2                 Reason_2     0.930004    2.534519
4                 Reason_4     0.807326    2.241905
5   Transportation Expense     0.626101    1.870304
9                 Children     0.357997    1.430461
7          Body Mass Index     0.287766    1.333445
6                      Age    -0.173487    0.840728
8                Education    -0.240742    0.786045
10                    Pets    -0.273198    0.760942
0                Intercept    -1.608133    0.200261

## Save the model

In [44]:
import pickle

In [45]:
with open('model', 'wb') as file:
    pickle.dump(logi_reg, file)

In [46]:
with open('scaler','wb') as file:
    pickle.dump(cust_scaler, file)